@startuml reset_navigation

skinparam shadow false
skinparam packageStyle rectangle
skinparam roundCorner 15
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #A80036
  ArrowColor #A80036
}

package "Navigation ResetPassword" {
  class "LoginForm" as Login <<navigationClass>>
  class "RecoverPage" as Recover <<navigationClass>>
  class "TokenInputPage" as TokenPage <<navigationClass>>
  class "NewPasswordPage" as NewPassPage <<navigationClass>>
  class "RecoverySuccess" as Success <<navigationClass>>

  Login --> Recover : <<navigationLink>>
  Recover --> TokenPage : <<navigationLink>>
  TokenPage --> NewPassPage : <<navigationLink>>
  NewPassPage --> Success : <<navigationLink>>
  Success --> Login : <<navigationLink>>
}
@enduml
