@startuml landingPage_navigation

skinparam shadow false
skinparam packageStyle rectangle
skinparam roundCorner 15
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #A80036
  ArrowColor #A80036
}

package "Navigation Landing Page" {
  class "Home" as Home <<navigationClass>> {
    {tag=isHome}
  }
  
  class "Menu" as Menu <<menu>>
  
  class "ShopCatalog" as Catalog <<navigationClass>>
  class "ShopPage" as ShopPage <<navigationClass>>
  class "ProductPage" as Product <<navigationClass>>
  
  class "SearchForm" as Search <<navigationClass>>
  class "SearchResults" as Results <<navigationClass>>
  
  class "AdminLogin" as Login <<navigationClass>>

  Home --> Menu : <<navigationLink>>
  Menu --> Catalog : <<navigationLink>>
  Menu --> Search : <<navigationLink>>
  Menu --> Login : <<navigationLink>>
  
  Catalog --> ShopPage : <<navigationLink>>
  ShopPage --> Product : <<navigationLink>>
  
  Search --> Results : <<navigationLink>>
  Results --> Product : <<navigationLink>>
}
@enduml
