@startuml
package "Requirements Login" {
  usecase "Iniciar Sesión" as Login <<processing>>
  usecase "Recuperar Contraseña" as Recover <<processing>>
  usecase "Ver Dashboard" as ViewDash <<browsing>>
  
  actor "Usuario" as User
}

package "Activity Login" {

}
package "Activity Reset Password" {

}

User --> Login
User --> Recover
Login ..> ViewDash 
Login <.. Recover 
@enduml
