@startuml customer_user_location_process_flow
skinparam shadow false
skinparam packageStyle rectangle
skinparam roundCorner 15
skinparam activity {
  BackgroundColor #FEFECE
  BorderColor #A80036
  ArrowColor #A80036
}

title Proceso Ubicación

start

:Boton Cambiar Ubicación pulsado;

:<<displayAction>>\nLista de Ciudades;

:<<userAction>>\nSeleccionar Ciudad;

:<<systemAction>>\nGuardar Ubicación;
stop
@enduml


