@startuml reset_content

skinparam shadow false
skinparam packageStyle rectangle
skinparam roundCorner 15
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #A80036
  ArrowColor #A80036
}

package "Content ResetPassword" {
  class Usuario <<content>> {
    - email : String
    + generarToken() : RecoveryToken
    + cambiarPassword(newPass: String) : void
  }

  class RecoveryToken <<content>> {
    - codigo : String
    - fechaExpiracion : Date
    - usado : Boolean
    + esValido() : Boolean
  }

  Usuario "1" -- "0..*" RecoveryToken : solicita >
}
@enduml
