@startuml adminPage_navigation

skinparam shadow false
skinparam packageStyle rectangle
skinparam roundCorner 15
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #A80036
  ArrowColor #A80036
}

package "Navigation Admin Page" {
  class "Dashboard" as Dash <<navigationClass>> {
    {tag=isHome}
  }
  
  class "AdminMenu" as Menu <<menu>>
  
  class "CreateShopPage" as CreateShop <<navigationClass>>
  class "AddProductPage" as AddProduct <<navigationClass>>
  class "LogoutAction" as Logout <<processClass>>
  
  class "ShopSuccess" as ShopOk <<navigationClass>>
  class "ProductSuccess" as ProdOk <<navigationClass>>

  Dash --> Menu : <<navigationLink>>
  
  Menu --> CreateShop : <<navigationLink>>
  Menu --> AddProduct : <<navigationLink>>
  Menu --> Logout : <<navigationLink>>
  
  CreateShop --> ShopOk : <<navigationLink>>
  ShopOk --> Dash : <<navigationLink>>
  
  AddProduct --> ProdOk : <<navigationLink>>
  ProdOk --> Dash : <<navigationLink>>
  
  Logout --> "LoginPage" : <<navigationLink>>
}
@enduml
